/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *button3;
  GtkWidget *button4;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *button2;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label4;
  GtkWidget *button1;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label5;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window1, 410, 150);
  GTK_WIDGET_SET_FLAGS (window1, GTK_CAN_FOCUS);
  gtk_window_set_title (GTK_WINDOW (window1), _("New launcher for desktop"));
  gtk_window_set_position (GTK_WINDOW (window1), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (window1), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (window1), 450, 150);
  gtk_window_set_resizable (GTK_WINDOW (window1), FALSE);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 144, 8);
  gtk_widget_set_size_request (entry1, 200, 24);
  GTK_WIDGET_SET_FLAGS (entry1, GTK_CAN_DEFAULT);
  gtk_entry_set_text (GTK_ENTRY (entry1), _("New icon"));

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 144, 40);
  gtk_widget_set_size_request (entry2, 200, 24);
  gtk_entry_set_text (GTK_ENTRY (entry2), _("xterm"));

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed1), entry3, 144, 72);
  gtk_widget_set_size_request (entry3, 200, 24);
  gtk_entry_set_text (GTK_ENTRY (entry3), _("xterm"));

  image1 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed1), image1, 8, 8);
  gtk_widget_set_size_request (image1, 56, 56);

  label1 = gtk_label_new (_(" Title"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 72, 8);
  gtk_widget_set_size_request (label1, 40, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label1), TRUE);

  button3 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 352, 40);
  gtk_widget_set_size_request (button3, 32, 24);
  gtk_button_set_relief (GTK_BUTTON (button3), GTK_RELIEF_NONE);

  button4 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed1), button4, 352, 72);
  gtk_widget_set_size_request (button4, 32, 24);
  gtk_button_set_relief (GTK_BUTTON (button4), GTK_RELIEF_NONE);

  label2 = gtk_label_new (_("Icon"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 72, 48);
  gtk_widget_set_size_request (label2, 56, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label2), TRUE);

  label3 = gtk_label_new (_("Executable"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 72, 80);
  gtk_widget_set_size_request (label3, 72, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label3), TRUE);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 64, 104);
  gtk_widget_set_size_request (button2, 112, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button2), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox1), label4, FALSE, FALSE, 0);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 240, 104);
  gtk_widget_set_size_request (button1, 120, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button1), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Create"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox2), label5, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) window1, "delete_event",
                    G_CALLBACK (on_window1_delete_event),
                    NULL);
  g_signal_connect ((gpointer) window1, "destroy_event",
                    G_CALLBACK (on_window1_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) window1, "show",
                    G_CALLBACK (on_window1_show),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, button3, "button3");
  GLADE_HOOKUP_OBJECT (window1, button4, "button4");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, button2, "button2");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");

  gtk_widget_grab_focus (window1);
  return window1;
}

GtkWidget*
create_fileselection1 (void)
{
  GtkWidget *fileselection1;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;

  fileselection1 = gtk_file_selection_new (_("Please select a XPM file"));
  gtk_container_set_border_width (GTK_CONTAINER (fileselection1), 10);
  gtk_window_set_position (GTK_WINDOW (fileselection1), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (fileselection1), TRUE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (fileselection1), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (fileselection1), GDK_WINDOW_TYPE_HINT_DIALOG);

  ok_button1 = GTK_FILE_SELECTION (fileselection1)->ok_button;
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);

  cancel_button1 = GTK_FILE_SELECTION (fileselection1)->cancel_button;
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) fileselection1, "delete_event",
                    G_CALLBACK (on_fileselection1_delete_event),
                    NULL);
  g_signal_connect ((gpointer) fileselection1, "destroy_event",
                    G_CALLBACK (on_fileselection1_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) ok_button1, "clicked",
                    G_CALLBACK (on_ok_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) cancel_button1, "clicked",
                    G_CALLBACK (on_cancel_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fileselection1, fileselection1, "fileselection1");
  GLADE_HOOKUP_OBJECT_NO_REF (fileselection1, ok_button1, "ok_button1");
  GLADE_HOOKUP_OBJECT_NO_REF (fileselection1, cancel_button1, "cancel_button1");

  return fileselection1;
}

GtkWidget*
create_fileselection2 (void)
{
  GtkWidget *fileselection2;
  GtkWidget *ok_button2;
  GtkWidget *cancel_button2;

  fileselection2 = gtk_file_selection_new (_("Please select a executable file"));
  gtk_container_set_border_width (GTK_CONTAINER (fileselection2), 10);
  gtk_window_set_modal (GTK_WINDOW (fileselection2), TRUE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (fileselection2), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (fileselection2), GDK_WINDOW_TYPE_HINT_DIALOG);

  ok_button2 = GTK_FILE_SELECTION (fileselection2)->ok_button;
  gtk_widget_show (ok_button2);
  GTK_WIDGET_SET_FLAGS (ok_button2, GTK_CAN_DEFAULT);

  cancel_button2 = GTK_FILE_SELECTION (fileselection2)->cancel_button;
  gtk_widget_show (cancel_button2);
  GTK_WIDGET_SET_FLAGS (cancel_button2, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) fileselection2, "delete_event",
                    G_CALLBACK (on_fileselection2_delete_event),
                    NULL);
  g_signal_connect ((gpointer) fileselection2, "destroy_event",
                    G_CALLBACK (on_fileselection2_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) ok_button2, "clicked",
                    G_CALLBACK (on_ok_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) cancel_button2, "clicked",
                    G_CALLBACK (on_cancel_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fileselection2, fileselection2, "fileselection2");
  GLADE_HOOKUP_OBJECT_NO_REF (fileselection2, ok_button2, "ok_button2");
  GLADE_HOOKUP_OBJECT_NO_REF (fileselection2, cancel_button2, "cancel_button2");

  return fileselection2;
}

